---
kind: golang.Generate
spec:
  experimentalFlags:
    - --experimental_allow_proto3_optional
  vtProtobufEnabled: true
  specs:
    - source: https://raw.githubusercontent.com/cosi-project/specification/a25fac056c642b32468b030387ab94c17bc3ba1d/proto/v1alpha1/resource.proto
      subdirectory: v1alpha1/
      genGateway: true
      external: false
    - source: https://raw.githubusercontent.com/cosi-project/specification/a25fac056c642b32468b030387ab94c17bc3ba1d/proto/v1alpha1/state.proto
      subdirectory: v1alpha1/
      genGateway: true
      external: false
    - source: https://raw.githubusercontent.com/cosi-project/specification/a25fac056c642b32468b030387ab94c17bc3ba1d/proto/v1alpha1/meta.proto
      subdirectory: v1alpha1/
      genGateway: true
      external: false
    - source: api/key_storage/key_storage.proto
      subdirectory: key_storage/
      genGateway: false
      external: false
---
kind: service.CodeCov
spec:
  targetThreshold: 45
