---
kind: auto.CommandConfig
name: directory-fun
spec:
  disableImage: true
---
kind: auto.CustomSteps
spec:
  steps:
    - name: run-directory-fun
      inputs:
        - directory-fun
      toplevel: true
---
kind: custom.Step
name: run-directory-fun
spec:
  makefile:
    enabled: true
    depends:
      - directory-fun
    script:
      - >-
        @$(ARTIFACTS)/directory-fun
  drone:
    enabled: true
---
kind: golang.Protobuf
spec:
  experimentalFlags:
    - --experimental_allow_proto3_optional
  specs:
    - source: https://raw.githubusercontent.com/smira/specification/resource-proto/proto/v1alpha1/resource/resource.proto
      subdirectory: v1alpha1/
