---
kind: golang.Protobuf
spec:
  experimentalFlags:
    - --experimental_allow_proto3_optional
  specs:
    - source: https://raw.githubusercontent.com/smira/specification/resource-proto/proto/v1alpha1/resource.proto
      subdirectory: v1alpha1/
    - source: https://raw.githubusercontent.com/smira/specification/resource-proto/proto/v1alpha1/state.proto
      subdirectory: v1alpha1/
    - source: https://raw.githubusercontent.com/smira/specification/resource-proto/proto/v1alpha1/runtime.proto
      subdirectory: v1alpha1/
