// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: v1alpha1/runtime.proto

package v1alpha1

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type DependencyKind int32

const (
	DependencyKind_WEAK   DependencyKind = 0
	DependencyKind_STRONG DependencyKind = 1
)

// Enum value maps for DependencyKind.
var (
	DependencyKind_name = map[int32]string{
		0: "WEAK",
		1: "STRONG",
	}
	DependencyKind_value = map[string]int32{
		"WEAK":   0,
		"STRONG": 1,
	}
)

func (x DependencyKind) Enum() *DependencyKind {
	p := new(DependencyKind)
	*p = x
	return p
}

func (x DependencyKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DependencyKind) Descriptor() protoreflect.EnumDescriptor {
	return file_v1alpha1_runtime_proto_enumTypes[0].Descriptor()
}

func (DependencyKind) Type() protoreflect.EnumType {
	return &file_v1alpha1_runtime_proto_enumTypes[0]
}

func (x DependencyKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DependencyKind.Descriptor instead.
func (DependencyKind) EnumDescriptor() ([]byte, []int) {
	return file_v1alpha1_runtime_proto_rawDescGZIP(), []int{0}
}

type RegisterControllerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ControllerName   string            `protobuf:"bytes,1,opt,name=controller_name,json=controllerName,proto3" json:"controller_name,omitempty"`
	ManagedResources *ManagedResources `protobuf:"bytes,2,opt,name=managed_resources,json=managedResources,proto3" json:"managed_resources,omitempty"`
}

func (x *RegisterControllerRequest) Reset() {
	*x = RegisterControllerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1alpha1_runtime_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterControllerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterControllerRequest) ProtoMessage() {}

func (x *RegisterControllerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_runtime_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterControllerRequest.ProtoReflect.Descriptor instead.
func (*RegisterControllerRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_runtime_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterControllerRequest) GetControllerName() string {
	if x != nil {
		return x.ControllerName
	}
	return ""
}

func (x *RegisterControllerRequest) GetManagedResources() *ManagedResources {
	if x != nil {
		return x.ManagedResources
	}
	return nil
}

type ManagedResources struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Type      string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *ManagedResources) Reset() {
	*x = ManagedResources{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1alpha1_runtime_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ManagedResources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagedResources) ProtoMessage() {}

func (x *ManagedResources) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_runtime_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagedResources.ProtoReflect.Descriptor instead.
func (*ManagedResources) Descriptor() ([]byte, []int) {
	return file_v1alpha1_runtime_proto_rawDescGZIP(), []int{1}
}

func (x *ManagedResources) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ManagedResources) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type RegisterControllerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ControllerToken string `protobuf:"bytes,1,opt,name=controller_token,json=controllerToken,proto3" json:"controller_token,omitempty"`
}

func (x *RegisterControllerResponse) Reset() {
	*x = RegisterControllerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1alpha1_runtime_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterControllerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterControllerResponse) ProtoMessage() {}

func (x *RegisterControllerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_runtime_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterControllerResponse.ProtoReflect.Descriptor instead.
func (*RegisterControllerResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_runtime_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterControllerResponse) GetControllerToken() string {
	if x != nil {
		return x.ControllerToken
	}
	return ""
}

type StartRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StartRequest) Reset() {
	*x = StartRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1alpha1_runtime_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRequest) ProtoMessage() {}

func (x *StartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_runtime_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRequest.ProtoReflect.Descriptor instead.
func (*StartRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_runtime_proto_rawDescGZIP(), []int{3}
}

type StartResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StartResponse) Reset() {
	*x = StartResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1alpha1_runtime_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartResponse) ProtoMessage() {}

func (x *StartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_runtime_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartResponse.ProtoReflect.Descriptor instead.
func (*StartResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_runtime_proto_rawDescGZIP(), []int{4}
}

type StopRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1alpha1_runtime_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_runtime_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_runtime_proto_rawDescGZIP(), []int{5}
}

type StopResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StopResponse) Reset() {
	*x = StopResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1alpha1_runtime_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResponse) ProtoMessage() {}

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_runtime_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResponse.ProtoReflect.Descriptor instead.
func (*StopResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_runtime_proto_rawDescGZIP(), []int{6}
}

type ReconcileEventsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ControllerToken string `protobuf:"bytes,1,opt,name=controller_token,json=controllerToken,proto3" json:"controller_token,omitempty"`
}

func (x *ReconcileEventsRequest) Reset() {
	*x = ReconcileEventsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1alpha1_runtime_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReconcileEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconcileEventsRequest) ProtoMessage() {}

func (x *ReconcileEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_runtime_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconcileEventsRequest.ProtoReflect.Descriptor instead.
func (*ReconcileEventsRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_runtime_proto_rawDescGZIP(), []int{7}
}

func (x *ReconcileEventsRequest) GetControllerToken() string {
	if x != nil {
		return x.ControllerToken
	}
	return ""
}

type ReconcileEventsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReconcileEventsResponse) Reset() {
	*x = ReconcileEventsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1alpha1_runtime_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReconcileEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconcileEventsResponse) ProtoMessage() {}

func (x *ReconcileEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_runtime_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconcileEventsResponse.ProtoReflect.Descriptor instead.
func (*ReconcileEventsResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_runtime_proto_rawDescGZIP(), []int{8}
}

type QueueReconcileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ControllerToken string `protobuf:"bytes,1,opt,name=controller_token,json=controllerToken,proto3" json:"controller_token,omitempty"`
}

func (x *QueueReconcileRequest) Reset() {
	*x = QueueReconcileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1alpha1_runtime_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueueReconcileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueReconcileRequest) ProtoMessage() {}

func (x *QueueReconcileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_runtime_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueReconcileRequest.ProtoReflect.Descriptor instead.
func (*QueueReconcileRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_runtime_proto_rawDescGZIP(), []int{9}
}

func (x *QueueReconcileRequest) GetControllerToken() string {
	if x != nil {
		return x.ControllerToken
	}
	return ""
}

type QueueReconcileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *QueueReconcileResponse) Reset() {
	*x = QueueReconcileResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1alpha1_runtime_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueueReconcileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueReconcileResponse) ProtoMessage() {}

func (x *QueueReconcileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_runtime_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueReconcileResponse.ProtoReflect.Descriptor instead.
func (*QueueReconcileResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_runtime_proto_rawDescGZIP(), []int{10}
}

type UpdateDependenciesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ControllerToken string        `protobuf:"bytes,1,opt,name=controller_token,json=controllerToken,proto3" json:"controller_token,omitempty"`
	Dependencies    []*Dependency `protobuf:"bytes,2,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
}

func (x *UpdateDependenciesRequest) Reset() {
	*x = UpdateDependenciesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1alpha1_runtime_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDependenciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDependenciesRequest) ProtoMessage() {}

func (x *UpdateDependenciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_runtime_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDependenciesRequest.ProtoReflect.Descriptor instead.
func (*UpdateDependenciesRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_runtime_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateDependenciesRequest) GetControllerToken() string {
	if x != nil {
		return x.ControllerToken
	}
	return ""
}

func (x *UpdateDependenciesRequest) GetDependencies() []*Dependency {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

type Dependency struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind      DependencyKind `protobuf:"varint,1,opt,name=kind,proto3,enum=runtime.DependencyKind" json:"kind,omitempty"`
	Namespace string         `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Type      string         `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Id        *string        `protobuf:"bytes,4,opt,name=id,proto3,oneof" json:"id,omitempty"`
}

func (x *Dependency) Reset() {
	*x = Dependency{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1alpha1_runtime_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Dependency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dependency) ProtoMessage() {}

func (x *Dependency) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_runtime_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dependency.ProtoReflect.Descriptor instead.
func (*Dependency) Descriptor() ([]byte, []int) {
	return file_v1alpha1_runtime_proto_rawDescGZIP(), []int{12}
}

func (x *Dependency) GetKind() DependencyKind {
	if x != nil {
		return x.Kind
	}
	return DependencyKind_WEAK
}

func (x *Dependency) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Dependency) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Dependency) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

type UpdateDependenciesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateDependenciesResponse) Reset() {
	*x = UpdateDependenciesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1alpha1_runtime_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDependenciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDependenciesResponse) ProtoMessage() {}

func (x *UpdateDependenciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_runtime_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDependenciesResponse.ProtoReflect.Descriptor instead.
func (*UpdateDependenciesResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_runtime_proto_rawDescGZIP(), []int{13}
}

type RuntimeGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ControllerToken string `protobuf:"bytes,1,opt,name=controller_token,json=controllerToken,proto3" json:"controller_token,omitempty"`
	Namespace       string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Type            string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Id              string `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RuntimeGetRequest) Reset() {
	*x = RuntimeGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1alpha1_runtime_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RuntimeGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeGetRequest) ProtoMessage() {}

func (x *RuntimeGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_runtime_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeGetRequest.ProtoReflect.Descriptor instead.
func (*RuntimeGetRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_runtime_proto_rawDescGZIP(), []int{14}
}

func (x *RuntimeGetRequest) GetControllerToken() string {
	if x != nil {
		return x.ControllerToken
	}
	return ""
}

func (x *RuntimeGetRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *RuntimeGetRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RuntimeGetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RuntimeGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resource *Resource `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
}

func (x *RuntimeGetResponse) Reset() {
	*x = RuntimeGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1alpha1_runtime_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RuntimeGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeGetResponse) ProtoMessage() {}

func (x *RuntimeGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_runtime_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeGetResponse.ProtoReflect.Descriptor instead.
func (*RuntimeGetResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_runtime_proto_rawDescGZIP(), []int{15}
}

func (x *RuntimeGetResponse) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

type RuntimeListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ControllerToken string `protobuf:"bytes,1,opt,name=controller_token,json=controllerToken,proto3" json:"controller_token,omitempty"`
	Namespace       string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Type            string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *RuntimeListRequest) Reset() {
	*x = RuntimeListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1alpha1_runtime_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RuntimeListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeListRequest) ProtoMessage() {}

func (x *RuntimeListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_runtime_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeListRequest.ProtoReflect.Descriptor instead.
func (*RuntimeListRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_runtime_proto_rawDescGZIP(), []int{16}
}

func (x *RuntimeListRequest) GetControllerToken() string {
	if x != nil {
		return x.ControllerToken
	}
	return ""
}

func (x *RuntimeListRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *RuntimeListRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type RuntimeListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resource *Resource `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
}

func (x *RuntimeListResponse) Reset() {
	*x = RuntimeListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1alpha1_runtime_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RuntimeListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeListResponse) ProtoMessage() {}

func (x *RuntimeListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_runtime_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeListResponse.ProtoReflect.Descriptor instead.
func (*RuntimeListResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_runtime_proto_rawDescGZIP(), []int{17}
}

func (x *RuntimeListResponse) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

type RuntimeWatchForRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ControllerToken string                    `protobuf:"bytes,1,opt,name=controller_token,json=controllerToken,proto3" json:"controller_token,omitempty"`
	Namespace       string                    `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Type            string                    `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Id              string                    `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	FinalizersEmpty *ConditionFinalizersEmpty `protobuf:"bytes,5,opt,name=finalizers_empty,json=finalizersEmpty,proto3" json:"finalizers_empty,omitempty"`
}

func (x *RuntimeWatchForRequest) Reset() {
	*x = RuntimeWatchForRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1alpha1_runtime_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RuntimeWatchForRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeWatchForRequest) ProtoMessage() {}

func (x *RuntimeWatchForRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_runtime_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeWatchForRequest.ProtoReflect.Descriptor instead.
func (*RuntimeWatchForRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_runtime_proto_rawDescGZIP(), []int{18}
}

func (x *RuntimeWatchForRequest) GetControllerToken() string {
	if x != nil {
		return x.ControllerToken
	}
	return ""
}

func (x *RuntimeWatchForRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *RuntimeWatchForRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RuntimeWatchForRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RuntimeWatchForRequest) GetFinalizersEmpty() *ConditionFinalizersEmpty {
	if x != nil {
		return x.FinalizersEmpty
	}
	return nil
}

type ConditionFinalizersEmpty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ConditionFinalizersEmpty) Reset() {
	*x = ConditionFinalizersEmpty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1alpha1_runtime_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConditionFinalizersEmpty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConditionFinalizersEmpty) ProtoMessage() {}

func (x *ConditionFinalizersEmpty) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_runtime_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConditionFinalizersEmpty.ProtoReflect.Descriptor instead.
func (*ConditionFinalizersEmpty) Descriptor() ([]byte, []int) {
	return file_v1alpha1_runtime_proto_rawDescGZIP(), []int{19}
}

type RuntimeWatchForResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resource *Resource `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
}

func (x *RuntimeWatchForResponse) Reset() {
	*x = RuntimeWatchForResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1alpha1_runtime_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RuntimeWatchForResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeWatchForResponse) ProtoMessage() {}

func (x *RuntimeWatchForResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_runtime_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeWatchForResponse.ProtoReflect.Descriptor instead.
func (*RuntimeWatchForResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_runtime_proto_rawDescGZIP(), []int{20}
}

func (x *RuntimeWatchForResponse) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

type RuntimeCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ControllerToken string    `protobuf:"bytes,1,opt,name=controller_token,json=controllerToken,proto3" json:"controller_token,omitempty"`
	Resource        *Resource `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
}

func (x *RuntimeCreateRequest) Reset() {
	*x = RuntimeCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1alpha1_runtime_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RuntimeCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeCreateRequest) ProtoMessage() {}

func (x *RuntimeCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_runtime_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeCreateRequest.ProtoReflect.Descriptor instead.
func (*RuntimeCreateRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_runtime_proto_rawDescGZIP(), []int{21}
}

func (x *RuntimeCreateRequest) GetControllerToken() string {
	if x != nil {
		return x.ControllerToken
	}
	return ""
}

func (x *RuntimeCreateRequest) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

type RuntimeCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RuntimeCreateResponse) Reset() {
	*x = RuntimeCreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1alpha1_runtime_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RuntimeCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeCreateResponse) ProtoMessage() {}

func (x *RuntimeCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_runtime_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeCreateResponse.ProtoReflect.Descriptor instead.
func (*RuntimeCreateResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_runtime_proto_rawDescGZIP(), []int{22}
}

type RuntimeUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ControllerToken string    `protobuf:"bytes,1,opt,name=controller_token,json=controllerToken,proto3" json:"controller_token,omitempty"`
	CurrentVersion  string    `protobuf:"bytes,2,opt,name=current_version,json=currentVersion,proto3" json:"current_version,omitempty"`
	NewResource     *Resource `protobuf:"bytes,3,opt,name=new_resource,json=newResource,proto3" json:"new_resource,omitempty"`
}

func (x *RuntimeUpdateRequest) Reset() {
	*x = RuntimeUpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1alpha1_runtime_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RuntimeUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeUpdateRequest) ProtoMessage() {}

func (x *RuntimeUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_runtime_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeUpdateRequest.ProtoReflect.Descriptor instead.
func (*RuntimeUpdateRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_runtime_proto_rawDescGZIP(), []int{23}
}

func (x *RuntimeUpdateRequest) GetControllerToken() string {
	if x != nil {
		return x.ControllerToken
	}
	return ""
}

func (x *RuntimeUpdateRequest) GetCurrentVersion() string {
	if x != nil {
		return x.CurrentVersion
	}
	return ""
}

func (x *RuntimeUpdateRequest) GetNewResource() *Resource {
	if x != nil {
		return x.NewResource
	}
	return nil
}

type RuntimeUpdateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RuntimeUpdateResponse) Reset() {
	*x = RuntimeUpdateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1alpha1_runtime_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RuntimeUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeUpdateResponse) ProtoMessage() {}

func (x *RuntimeUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_runtime_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeUpdateResponse.ProtoReflect.Descriptor instead.
func (*RuntimeUpdateResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_runtime_proto_rawDescGZIP(), []int{24}
}

type RuntimeTeardownRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ControllerToken string `protobuf:"bytes,1,opt,name=controller_token,json=controllerToken,proto3" json:"controller_token,omitempty"`
	Namespace       string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Type            string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Id              string `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RuntimeTeardownRequest) Reset() {
	*x = RuntimeTeardownRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1alpha1_runtime_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RuntimeTeardownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeTeardownRequest) ProtoMessage() {}

func (x *RuntimeTeardownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_runtime_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeTeardownRequest.ProtoReflect.Descriptor instead.
func (*RuntimeTeardownRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_runtime_proto_rawDescGZIP(), []int{25}
}

func (x *RuntimeTeardownRequest) GetControllerToken() string {
	if x != nil {
		return x.ControllerToken
	}
	return ""
}

func (x *RuntimeTeardownRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *RuntimeTeardownRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RuntimeTeardownRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RuntimeTeardownResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ready bool `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
}

func (x *RuntimeTeardownResponse) Reset() {
	*x = RuntimeTeardownResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1alpha1_runtime_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RuntimeTeardownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeTeardownResponse) ProtoMessage() {}

func (x *RuntimeTeardownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_runtime_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeTeardownResponse.ProtoReflect.Descriptor instead.
func (*RuntimeTeardownResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_runtime_proto_rawDescGZIP(), []int{26}
}

func (x *RuntimeTeardownResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

type RuntimeDestroyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ControllerToken string `protobuf:"bytes,1,opt,name=controller_token,json=controllerToken,proto3" json:"controller_token,omitempty"`
	Namespace       string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Type            string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Id              string `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RuntimeDestroyRequest) Reset() {
	*x = RuntimeDestroyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1alpha1_runtime_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RuntimeDestroyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeDestroyRequest) ProtoMessage() {}

func (x *RuntimeDestroyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_runtime_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeDestroyRequest.ProtoReflect.Descriptor instead.
func (*RuntimeDestroyRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_runtime_proto_rawDescGZIP(), []int{27}
}

func (x *RuntimeDestroyRequest) GetControllerToken() string {
	if x != nil {
		return x.ControllerToken
	}
	return ""
}

func (x *RuntimeDestroyRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *RuntimeDestroyRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RuntimeDestroyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RuntimeDestroyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RuntimeDestroyResponse) Reset() {
	*x = RuntimeDestroyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1alpha1_runtime_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RuntimeDestroyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeDestroyResponse) ProtoMessage() {}

func (x *RuntimeDestroyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_runtime_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeDestroyResponse.ProtoReflect.Descriptor instead.
func (*RuntimeDestroyResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_runtime_proto_rawDescGZIP(), []int{28}
}

type RuntimeAddFinalizerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ControllerToken string   `protobuf:"bytes,1,opt,name=controller_token,json=controllerToken,proto3" json:"controller_token,omitempty"`
	Namespace       string   `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Type            string   `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Id              string   `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	Finalizers      []string `protobuf:"bytes,5,rep,name=finalizers,proto3" json:"finalizers,omitempty"`
}

func (x *RuntimeAddFinalizerRequest) Reset() {
	*x = RuntimeAddFinalizerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1alpha1_runtime_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RuntimeAddFinalizerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeAddFinalizerRequest) ProtoMessage() {}

func (x *RuntimeAddFinalizerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_runtime_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeAddFinalizerRequest.ProtoReflect.Descriptor instead.
func (*RuntimeAddFinalizerRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_runtime_proto_rawDescGZIP(), []int{29}
}

func (x *RuntimeAddFinalizerRequest) GetControllerToken() string {
	if x != nil {
		return x.ControllerToken
	}
	return ""
}

func (x *RuntimeAddFinalizerRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *RuntimeAddFinalizerRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RuntimeAddFinalizerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RuntimeAddFinalizerRequest) GetFinalizers() []string {
	if x != nil {
		return x.Finalizers
	}
	return nil
}

type RuntimeAddFinalizerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RuntimeAddFinalizerResponse) Reset() {
	*x = RuntimeAddFinalizerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1alpha1_runtime_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RuntimeAddFinalizerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeAddFinalizerResponse) ProtoMessage() {}

func (x *RuntimeAddFinalizerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_runtime_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeAddFinalizerResponse.ProtoReflect.Descriptor instead.
func (*RuntimeAddFinalizerResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_runtime_proto_rawDescGZIP(), []int{30}
}

type RuntimeRemoveFinalizerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ControllerToken string   `protobuf:"bytes,1,opt,name=controller_token,json=controllerToken,proto3" json:"controller_token,omitempty"`
	Namespace       string   `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Type            string   `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Id              string   `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	Finalizers      []string `protobuf:"bytes,5,rep,name=finalizers,proto3" json:"finalizers,omitempty"`
}

func (x *RuntimeRemoveFinalizerRequest) Reset() {
	*x = RuntimeRemoveFinalizerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1alpha1_runtime_proto_msgTypes[31]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RuntimeRemoveFinalizerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeRemoveFinalizerRequest) ProtoMessage() {}

func (x *RuntimeRemoveFinalizerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_runtime_proto_msgTypes[31]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeRemoveFinalizerRequest.ProtoReflect.Descriptor instead.
func (*RuntimeRemoveFinalizerRequest) Descriptor() ([]byte, []int) {
	return file_v1alpha1_runtime_proto_rawDescGZIP(), []int{31}
}

func (x *RuntimeRemoveFinalizerRequest) GetControllerToken() string {
	if x != nil {
		return x.ControllerToken
	}
	return ""
}

func (x *RuntimeRemoveFinalizerRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *RuntimeRemoveFinalizerRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RuntimeRemoveFinalizerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RuntimeRemoveFinalizerRequest) GetFinalizers() []string {
	if x != nil {
		return x.Finalizers
	}
	return nil
}

type RuntimeRemoveFinalizerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RuntimeRemoveFinalizerResponse) Reset() {
	*x = RuntimeRemoveFinalizerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1alpha1_runtime_proto_msgTypes[32]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RuntimeRemoveFinalizerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeRemoveFinalizerResponse) ProtoMessage() {}

func (x *RuntimeRemoveFinalizerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_runtime_proto_msgTypes[32]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeRemoveFinalizerResponse.ProtoReflect.Descriptor instead.
func (*RuntimeRemoveFinalizerResponse) Descriptor() ([]byte, []int) {
	return file_v1alpha1_runtime_proto_rawDescGZIP(), []int{32}
}

var File_v1alpha1_runtime_proto protoreflect.FileDescriptor

var file_v1alpha1_runtime_proto_rawDesc = []byte{
	0x0a, 0x16, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2f, 0x72, 0x75, 0x6e, 0x74, 0x69,
	0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d,
	0x65, 0x1a, 0x17, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2f, 0x72, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8c, 0x01, 0x0a, 0x19, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x6f, 0x6e, 0x74,
	0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x46, 0x0a, 0x11, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x64, 0x5f, 0x72, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x72,
	0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x64, 0x52, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x52, 0x10, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x64,
	0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x22, 0x44, 0x0a, 0x10, 0x4d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x64, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x12, 0x1c, 0x0a,
	0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22,
	0x47, 0x0a, 0x1a, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x74, 0x72,
	0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a,
	0x10, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x5f, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c,
	0x6c, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x0e, 0x0a, 0x0c, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x0f, 0x0a, 0x0d, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x0d, 0x0a, 0x0b, 0x53, 0x74, 0x6f,
	0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x0e, 0x0a, 0x0c, 0x53, 0x74, 0x6f, 0x70,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x43, 0x0a, 0x16, 0x52, 0x65, 0x63, 0x6f,
	0x6e, 0x63, 0x69, 0x6c, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x29, 0x0a, 0x10, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72,
	0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x19, 0x0a,
	0x17, 0x52, 0x65, 0x63, 0x6f, 0x6e, 0x63, 0x69, 0x6c, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x42, 0x0a, 0x15, 0x51, 0x75, 0x65, 0x75,
	0x65, 0x52, 0x65, 0x63, 0x6f, 0x6e, 0x63, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x29, 0x0a, 0x10, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x5f,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x63, 0x6f, 0x6e,
	0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x18, 0x0a, 0x16,
	0x51, 0x75, 0x65, 0x75, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x6e, 0x63, 0x69, 0x6c, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x7f, 0x0a, 0x19, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x29, 0x0a, 0x10, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65,
	0x72, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x63,
	0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x37,
	0x0a, 0x0c, 0x64, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x44,
	0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x79, 0x52, 0x0c, 0x64, 0x65, 0x70, 0x65, 0x6e,
	0x64, 0x65, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x22, 0x87, 0x01, 0x0a, 0x0a, 0x44, 0x65, 0x70, 0x65,
	0x6e, 0x64, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x2b, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x44,
	0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x79, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x04, 0x6b,
	0x69, 0x6e, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x13, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x00, 0x52, 0x02, 0x69, 0x64, 0x88, 0x01, 0x01, 0x42, 0x05, 0x0a, 0x03, 0x5f, 0x69,
	0x64, 0x22, 0x1c, 0x0a, 0x1a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x65, 0x70, 0x65, 0x6e,
	0x64, 0x65, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x80, 0x01, 0x0a, 0x11, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x29, 0x0a, 0x10, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c,
	0x6c, 0x65, 0x72, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x44, 0x0a, 0x12, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x72, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x08,
	0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x22, 0x71, 0x0a, 0x12, 0x52, 0x75, 0x6e, 0x74,
	0x69, 0x6d, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x29,
	0x0a, 0x10, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x5f, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f,
	0x6c, 0x6c, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d,
	0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61,
	0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x45, 0x0a, 0x13, 0x52,
	0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2e, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e,
	0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x22, 0xd3, 0x01, 0x0a, 0x16, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x57, 0x61,
	0x74, 0x63, 0x68, 0x46, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x29, 0x0a,
	0x10, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x5f, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c,
	0x6c, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d,
	0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x4c, 0x0a, 0x10, 0x66, 0x69,
	0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x72, 0x73, 0x5f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x43,
	0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65,
	0x72, 0x73, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x0f, 0x66, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a,
	0x65, 0x72, 0x73, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x1a, 0x0a, 0x18, 0x43, 0x6f, 0x6e, 0x64,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x72, 0x73, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x22, 0x49, 0x0a, 0x17, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x57,
	0x61, 0x74, 0x63, 0x68, 0x46, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x2e, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x22,
	0x71, 0x0a, 0x14, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x29, 0x0a, 0x10, 0x63, 0x6f, 0x6e, 0x74, 0x72,
	0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x12, 0x2e, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e,
	0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x22, 0x17, 0x0a, 0x15, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xa1, 0x01, 0x0a, 0x14,
	0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x29, 0x0a, 0x10, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c,
	0x65, 0x72, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f,
	0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12,
	0x27, 0x0a, 0x0f, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e,
	0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x35, 0x0a, 0x0c, 0x6e, 0x65, 0x77, 0x5f,
	0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x52, 0x0b, 0x6e, 0x65, 0x77, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x22,
	0x17, 0x0a, 0x15, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x85, 0x01, 0x0a, 0x16, 0x52, 0x75, 0x6e,
	0x74, 0x69, 0x6d, 0x65, 0x54, 0x65, 0x61, 0x72, 0x64, 0x6f, 0x77, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x29, 0x0a, 0x10, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65,
	0x72, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x63,
	0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1c,
	0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x2f, 0x0a, 0x17, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x54, 0x65, 0x61, 0x72, 0x64,
	0x6f, 0x77, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x72,
	0x65, 0x61, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x72, 0x65, 0x61, 0x64,
	0x79, 0x22, 0x84, 0x01, 0x0a, 0x15, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x44, 0x65, 0x73,
	0x74, 0x72, 0x6f, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x29, 0x0a, 0x10, 0x63,
	0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65,
	0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x18, 0x0a, 0x16, 0x52, 0x75, 0x6e, 0x74,
	0x69, 0x6d, 0x65, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0xa9, 0x01, 0x0a, 0x1a, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x41, 0x64,
	0x64, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x29, 0x0a, 0x10, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x5f,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x63, 0x6f, 0x6e,
	0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1c, 0x0a, 0x09,
	0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1e,
	0x0a, 0x0a, 0x66, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x72, 0x73, 0x18, 0x05, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x0a, 0x66, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x72, 0x73, 0x22, 0x1d,
	0x0a, 0x1b, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x41, 0x64, 0x64, 0x46, 0x69, 0x6e, 0x61,
	0x6c, 0x69, 0x7a, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xac, 0x01,
	0x0a, 0x1d, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x46,
	0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x29, 0x0a, 0x10, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x5f, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x63, 0x6f, 0x6e, 0x74, 0x72,
	0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61,
	0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e,
	0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1e, 0x0a, 0x0a,
	0x66, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x72, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x0a, 0x66, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x72, 0x73, 0x22, 0x20, 0x0a, 0x1e,
	0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x46, 0x69, 0x6e,
	0x61, 0x6c, 0x69, 0x7a, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2a, 0x26,
	0x0a, 0x0e, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x79, 0x4b, 0x69, 0x6e, 0x64,
	0x12, 0x08, 0x0a, 0x04, 0x57, 0x45, 0x41, 0x4b, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x54,
	0x52, 0x4f, 0x4e, 0x47, 0x10, 0x01, 0x32, 0xdf, 0x01, 0x0a, 0x11, 0x43, 0x6f, 0x6e, 0x74, 0x72,
	0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x5d, 0x0a, 0x12,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c,
	0x65, 0x72, 0x12, 0x22, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65,
	0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c,
	0x6c, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x05, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x12, 0x15, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x72, 0x75,
	0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x04, 0x53, 0x74, 0x6f, 0x70, 0x12, 0x14, 0x2e, 0x72, 0x75,
	0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x15, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x53, 0x74, 0x6f, 0x70,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xdd, 0x07, 0x0a, 0x11, 0x43, 0x6f, 0x6e,
	0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x41, 0x64, 0x61, 0x70, 0x74, 0x65, 0x72, 0x12, 0x56,
	0x0a, 0x0f, 0x52, 0x65, 0x63, 0x6f, 0x6e, 0x63, 0x69, 0x6c, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x73, 0x12, 0x1f, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x52, 0x65, 0x63, 0x6f,
	0x6e, 0x63, 0x69, 0x6c, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x20, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x52, 0x65, 0x63,
	0x6f, 0x6e, 0x63, 0x69, 0x6c, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x12, 0x51, 0x0a, 0x0e, 0x51, 0x75, 0x65, 0x75, 0x65, 0x52,
	0x65, 0x63, 0x6f, 0x6e, 0x63, 0x69, 0x6c, 0x65, 0x12, 0x1e, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69,
	0x6d, 0x65, 0x2e, 0x51, 0x75, 0x65, 0x75, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x6e, 0x63, 0x69, 0x6c,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69,
	0x6d, 0x65, 0x2e, 0x51, 0x75, 0x65, 0x75, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x6e, 0x63, 0x69, 0x6c,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5d, 0x0a, 0x12, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x12,
	0x22, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x69, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12,
	0x1a, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d,
	0x65, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x72, 0x75,
	0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x1b, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x52, 0x75, 0x6e, 0x74, 0x69,
	0x6d, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e,
	0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x12, 0x4d, 0x0a,
	0x08, 0x57, 0x61, 0x74, 0x63, 0x68, 0x46, 0x6f, 0x72, 0x12, 0x1f, 0x2e, 0x72, 0x75, 0x6e, 0x74,
	0x69, 0x6d, 0x65, 0x2e, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x57, 0x61, 0x74, 0x63, 0x68,
	0x46, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x72, 0x75, 0x6e,
	0x74, 0x69, 0x6d, 0x65, 0x2e, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x57, 0x61, 0x74, 0x63,
	0x68, 0x46, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a, 0x06,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x1d, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65,
	0x2e, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e,
	0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12,
	0x1d, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d,
	0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e,
	0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4d,
	0x0a, 0x08, 0x54, 0x65, 0x61, 0x72, 0x64, 0x6f, 0x77, 0x6e, 0x12, 0x1f, 0x2e, 0x72, 0x75, 0x6e,
	0x74, 0x69, 0x6d, 0x65, 0x2e, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x54, 0x65, 0x61, 0x72,
	0x64, 0x6f, 0x77, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x72, 0x75,
	0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x54, 0x65, 0x61,
	0x72, 0x64, 0x6f, 0x77, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4a, 0x0a,
	0x07, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x12, 0x1e, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69,
	0x6d, 0x65, 0x2e, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69,
	0x6d, 0x65, 0x2e, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x59, 0x0a, 0x0c, 0x41, 0x64, 0x64,
	0x46, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x72, 0x12, 0x23, 0x2e, 0x72, 0x75, 0x6e, 0x74,
	0x69, 0x6d, 0x65, 0x2e, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x41, 0x64, 0x64, 0x46, 0x69,
	0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24,
	0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65,
	0x41, 0x64, 0x64, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x62, 0x0a, 0x0f, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x46, 0x69,
	0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x72, 0x12, 0x26, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d,
	0x65, 0x2e, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x46,
	0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x27, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d,
	0x65, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x61, 0x6c, 0x6f, 0x73, 0x2d, 0x73, 0x79, 0x73,
	0x74, 0x65, 0x6d, 0x73, 0x2f, 0x6f, 0x73, 0x2d, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1alpha1_runtime_proto_rawDescOnce sync.Once
	file_v1alpha1_runtime_proto_rawDescData = file_v1alpha1_runtime_proto_rawDesc
)

func file_v1alpha1_runtime_proto_rawDescGZIP() []byte {
	file_v1alpha1_runtime_proto_rawDescOnce.Do(func() {
		file_v1alpha1_runtime_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1alpha1_runtime_proto_rawDescData)
	})
	return file_v1alpha1_runtime_proto_rawDescData
}

var file_v1alpha1_runtime_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1alpha1_runtime_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_v1alpha1_runtime_proto_goTypes = []interface{}{
	(DependencyKind)(0),                    // 0: runtime.DependencyKind
	(*RegisterControllerRequest)(nil),      // 1: runtime.RegisterControllerRequest
	(*ManagedResources)(nil),               // 2: runtime.ManagedResources
	(*RegisterControllerResponse)(nil),     // 3: runtime.RegisterControllerResponse
	(*StartRequest)(nil),                   // 4: runtime.StartRequest
	(*StartResponse)(nil),                  // 5: runtime.StartResponse
	(*StopRequest)(nil),                    // 6: runtime.StopRequest
	(*StopResponse)(nil),                   // 7: runtime.StopResponse
	(*ReconcileEventsRequest)(nil),         // 8: runtime.ReconcileEventsRequest
	(*ReconcileEventsResponse)(nil),        // 9: runtime.ReconcileEventsResponse
	(*QueueReconcileRequest)(nil),          // 10: runtime.QueueReconcileRequest
	(*QueueReconcileResponse)(nil),         // 11: runtime.QueueReconcileResponse
	(*UpdateDependenciesRequest)(nil),      // 12: runtime.UpdateDependenciesRequest
	(*Dependency)(nil),                     // 13: runtime.Dependency
	(*UpdateDependenciesResponse)(nil),     // 14: runtime.UpdateDependenciesResponse
	(*RuntimeGetRequest)(nil),              // 15: runtime.RuntimeGetRequest
	(*RuntimeGetResponse)(nil),             // 16: runtime.RuntimeGetResponse
	(*RuntimeListRequest)(nil),             // 17: runtime.RuntimeListRequest
	(*RuntimeListResponse)(nil),            // 18: runtime.RuntimeListResponse
	(*RuntimeWatchForRequest)(nil),         // 19: runtime.RuntimeWatchForRequest
	(*ConditionFinalizersEmpty)(nil),       // 20: runtime.ConditionFinalizersEmpty
	(*RuntimeWatchForResponse)(nil),        // 21: runtime.RuntimeWatchForResponse
	(*RuntimeCreateRequest)(nil),           // 22: runtime.RuntimeCreateRequest
	(*RuntimeCreateResponse)(nil),          // 23: runtime.RuntimeCreateResponse
	(*RuntimeUpdateRequest)(nil),           // 24: runtime.RuntimeUpdateRequest
	(*RuntimeUpdateResponse)(nil),          // 25: runtime.RuntimeUpdateResponse
	(*RuntimeTeardownRequest)(nil),         // 26: runtime.RuntimeTeardownRequest
	(*RuntimeTeardownResponse)(nil),        // 27: runtime.RuntimeTeardownResponse
	(*RuntimeDestroyRequest)(nil),          // 28: runtime.RuntimeDestroyRequest
	(*RuntimeDestroyResponse)(nil),         // 29: runtime.RuntimeDestroyResponse
	(*RuntimeAddFinalizerRequest)(nil),     // 30: runtime.RuntimeAddFinalizerRequest
	(*RuntimeAddFinalizerResponse)(nil),    // 31: runtime.RuntimeAddFinalizerResponse
	(*RuntimeRemoveFinalizerRequest)(nil),  // 32: runtime.RuntimeRemoveFinalizerRequest
	(*RuntimeRemoveFinalizerResponse)(nil), // 33: runtime.RuntimeRemoveFinalizerResponse
	(*Resource)(nil),                       // 34: resource.Resource
}
var file_v1alpha1_runtime_proto_depIdxs = []int32{
	2,  // 0: runtime.RegisterControllerRequest.managed_resources:type_name -> runtime.ManagedResources
	13, // 1: runtime.UpdateDependenciesRequest.dependencies:type_name -> runtime.Dependency
	0,  // 2: runtime.Dependency.kind:type_name -> runtime.DependencyKind
	34, // 3: runtime.RuntimeGetResponse.resource:type_name -> resource.Resource
	34, // 4: runtime.RuntimeListResponse.resource:type_name -> resource.Resource
	20, // 5: runtime.RuntimeWatchForRequest.finalizers_empty:type_name -> runtime.ConditionFinalizersEmpty
	34, // 6: runtime.RuntimeWatchForResponse.resource:type_name -> resource.Resource
	34, // 7: runtime.RuntimeCreateRequest.resource:type_name -> resource.Resource
	34, // 8: runtime.RuntimeUpdateRequest.new_resource:type_name -> resource.Resource
	1,  // 9: runtime.ControllerRuntime.RegisterController:input_type -> runtime.RegisterControllerRequest
	4,  // 10: runtime.ControllerRuntime.Start:input_type -> runtime.StartRequest
	6,  // 11: runtime.ControllerRuntime.Stop:input_type -> runtime.StopRequest
	8,  // 12: runtime.ControllerAdapter.ReconcileEvents:input_type -> runtime.ReconcileEventsRequest
	10, // 13: runtime.ControllerAdapter.QueueReconcile:input_type -> runtime.QueueReconcileRequest
	12, // 14: runtime.ControllerAdapter.UpdateDependencies:input_type -> runtime.UpdateDependenciesRequest
	15, // 15: runtime.ControllerAdapter.Get:input_type -> runtime.RuntimeGetRequest
	17, // 16: runtime.ControllerAdapter.List:input_type -> runtime.RuntimeListRequest
	19, // 17: runtime.ControllerAdapter.WatchFor:input_type -> runtime.RuntimeWatchForRequest
	22, // 18: runtime.ControllerAdapter.Create:input_type -> runtime.RuntimeCreateRequest
	24, // 19: runtime.ControllerAdapter.Update:input_type -> runtime.RuntimeUpdateRequest
	26, // 20: runtime.ControllerAdapter.Teardown:input_type -> runtime.RuntimeTeardownRequest
	28, // 21: runtime.ControllerAdapter.Destroy:input_type -> runtime.RuntimeDestroyRequest
	30, // 22: runtime.ControllerAdapter.AddFinalizer:input_type -> runtime.RuntimeAddFinalizerRequest
	32, // 23: runtime.ControllerAdapter.RemoveFinalizer:input_type -> runtime.RuntimeRemoveFinalizerRequest
	3,  // 24: runtime.ControllerRuntime.RegisterController:output_type -> runtime.RegisterControllerResponse
	5,  // 25: runtime.ControllerRuntime.Start:output_type -> runtime.StartResponse
	7,  // 26: runtime.ControllerRuntime.Stop:output_type -> runtime.StopResponse
	9,  // 27: runtime.ControllerAdapter.ReconcileEvents:output_type -> runtime.ReconcileEventsResponse
	11, // 28: runtime.ControllerAdapter.QueueReconcile:output_type -> runtime.QueueReconcileResponse
	14, // 29: runtime.ControllerAdapter.UpdateDependencies:output_type -> runtime.UpdateDependenciesResponse
	16, // 30: runtime.ControllerAdapter.Get:output_type -> runtime.RuntimeGetResponse
	18, // 31: runtime.ControllerAdapter.List:output_type -> runtime.RuntimeListResponse
	21, // 32: runtime.ControllerAdapter.WatchFor:output_type -> runtime.RuntimeWatchForResponse
	23, // 33: runtime.ControllerAdapter.Create:output_type -> runtime.RuntimeCreateResponse
	25, // 34: runtime.ControllerAdapter.Update:output_type -> runtime.RuntimeUpdateResponse
	27, // 35: runtime.ControllerAdapter.Teardown:output_type -> runtime.RuntimeTeardownResponse
	29, // 36: runtime.ControllerAdapter.Destroy:output_type -> runtime.RuntimeDestroyResponse
	31, // 37: runtime.ControllerAdapter.AddFinalizer:output_type -> runtime.RuntimeAddFinalizerResponse
	33, // 38: runtime.ControllerAdapter.RemoveFinalizer:output_type -> runtime.RuntimeRemoveFinalizerResponse
	24, // [24:39] is the sub-list for method output_type
	9,  // [9:24] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_v1alpha1_runtime_proto_init() }
func file_v1alpha1_runtime_proto_init() {
	if File_v1alpha1_runtime_proto != nil {
		return
	}
	file_v1alpha1_resource_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_v1alpha1_runtime_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterControllerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1alpha1_runtime_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ManagedResources); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1alpha1_runtime_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterControllerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1alpha1_runtime_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1alpha1_runtime_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1alpha1_runtime_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1alpha1_runtime_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1alpha1_runtime_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReconcileEventsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1alpha1_runtime_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReconcileEventsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1alpha1_runtime_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueueReconcileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1alpha1_runtime_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueueReconcileResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1alpha1_runtime_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDependenciesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1alpha1_runtime_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Dependency); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1alpha1_runtime_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDependenciesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1alpha1_runtime_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RuntimeGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1alpha1_runtime_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RuntimeGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1alpha1_runtime_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RuntimeListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1alpha1_runtime_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RuntimeListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1alpha1_runtime_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RuntimeWatchForRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1alpha1_runtime_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConditionFinalizersEmpty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1alpha1_runtime_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RuntimeWatchForResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1alpha1_runtime_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RuntimeCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1alpha1_runtime_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RuntimeCreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1alpha1_runtime_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RuntimeUpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1alpha1_runtime_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RuntimeUpdateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1alpha1_runtime_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RuntimeTeardownRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1alpha1_runtime_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RuntimeTeardownResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1alpha1_runtime_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RuntimeDestroyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1alpha1_runtime_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RuntimeDestroyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1alpha1_runtime_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RuntimeAddFinalizerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1alpha1_runtime_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RuntimeAddFinalizerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1alpha1_runtime_proto_msgTypes[31].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RuntimeRemoveFinalizerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1alpha1_runtime_proto_msgTypes[32].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RuntimeRemoveFinalizerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_v1alpha1_runtime_proto_msgTypes[12].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1alpha1_runtime_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_v1alpha1_runtime_proto_goTypes,
		DependencyIndexes: file_v1alpha1_runtime_proto_depIdxs,
		EnumInfos:         file_v1alpha1_runtime_proto_enumTypes,
		MessageInfos:      file_v1alpha1_runtime_proto_msgTypes,
	}.Build()
	File_v1alpha1_runtime_proto = out.File
	file_v1alpha1_runtime_proto_rawDesc = nil
	file_v1alpha1_runtime_proto_goTypes = nil
	file_v1alpha1_runtime_proto_depIdxs = nil
}
